# Generated by Django 3.2.23 on 2024-01-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0085_auto_20240122_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='opining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='supplier',
            name='opining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
