# Generated by Django 3.2.23 on 2024-01-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0087_auto_20240123_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='opining_balance',
        ),
    ]
