# Generated by Django 3.2.23 on 2024-01-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0088_remove_supplier_opining_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='opining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
