# Generated by Django 3.2.23 on 2024-01-23 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0089_supplier_opining_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='opining_balance',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='opining_balance',
        ),
    ]
