# Generated by Django 3.2.23 on 2024-01-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0090_auto_20240123_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='opening',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
