# Generated by Django 3.2.23 on 2024-01-23 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0092_remove_supplier_opening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='on_him_money',
        ),
    ]
