# Generated by Django 3.2.23 on 2024-01-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0094_supplier_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
