# Generated by Django 3.2.23 on 2024-01-23 01:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0095_supplier_opening_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='balance',
        ),
        migrations.CreateModel(
            name='SupplierPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=datetime.date(2024, 1, 23))),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.supplier')),
            ],
        ),
    ]
