# Generated by Django 3.2.23 on 2024-01-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0096_auto_20240123_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
